Alldata <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
DataForFebFirstTwodays <- subset(Alldata,Date %in% c("1/2/2007","2/2/2007"))
library(reshape2)
reshapedata <- melt(DataForFebFirstTwodays,id=c("Date","Time"),measure.vars=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
x <- as.POSIXlt(paste(reshapedata$Date, reshapedata$Time), format="%d/%m/%Y %H:%M:%S")
y <- reshapedata$value
par(mar=c(2,4,2,2))
with(reshapedata,plot(x,value, type ="l",xlab="",ylab="Energy sub metering",main=""))
with(subset(reshapedata,variable == "Sub_metering_1"),lines(x,y,col="black"))
with(subset(reshapedata,variable == "Sub_metering_2"),lines(x,y,col="red"))
with(subset(reshapedata,variable == "Sub_metering_3"),lines(x,y,col="blue"))
legend("topright",c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty=1, col=c("black", "red", "blue"))
dev.copy(png,file="plot3.png",width = 480, height = 480)
dev.off()
